<?php

/**
 *  2Moons
 *  Copyright (C) 2011  Slaver
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @package 2Moons
 * @author Slaver <slaver7@gmail.com>
 * @author Razzo <webmaster@razzo.org> (Italian translation)
 * @copyright 2009 Lucky <lucky@xgproyect.net> (XGProyecto)
 * @copyright 2011 Slaver <slaver7@gmail.com> (Fork/2Moons)
 * @license http://www.gnu.org/licenses/gpl.html GNU GPLv3 License
 * @version 1.5 (2011-07-31)
 * @info $Id: CUSTOM.php 2126 2012-03-11 21:11:32Z slaver7 $
 * @link http://code.google.com/p/2moons/
 */

//SHORT NAMES FOR COMBAT REPORTS

$LNG['shortNames'] = array (
	202 => 'Cargo Leggero',
	203 => 'Cargo Pesante',
	204 => 'Caccia Leggero',
	205 => 'Caccia Pesante',
	206 => 'Incrociatore ',
	207 => 'Nave da Battaglia',
	208 => 'Colonizzatrice',
	209 => 'Riciclatrice',
	210 => 'Sonda spia',
	211 => 'Bombardiere',
	212 => 'Satellite Solare',
	213 => 'Cacciatorpediniere',
	214 => 'Corazzata',
	215 => 'Incrociatore da Battaglia',
	216 => 'Morte Nera',
	217 => 'Cargo Avanzato',
	218 => 'Avatar',
	219 => 'Giga Riciclatrice',
	220 => 'Collezionista MO Intergalattica',

	401 => 'Lanciamissili',
	402 => 'Laser Leggero',
	403 => 'Laser Pesante',
	404 => 'Cannone Gauss',
	405 => 'Cannone Ionico',
	406 => 'Cannone al Plasma',
	407 => 'Cupola Scudo',
	408 => 'Cupola Scudo Potenziata',
	409 => 'Scudo Atmosferico',
	410 => 'Cannone Gravitonico',
	411 => 'Globo Difensivo Orbitale',
);

$LNG['bonus'] = array(
	'Attack'			=> '+%f%% Angriff',
	'Defensive'			=> '+%f%% Verteidigung',
	'Shield'			=> '+%f%% Schild',
	'BuildTime'			=> '-%f%% Bauzeit',
	'ResearchTime'		=> '-%f%% Forschungszeit',
	'ShipTime'			=> '-%f%% Schiffbauzeit',
	'DefensiveTime'		=> '-%f%% Verteidungsbauzeit',
	'Resource'			=> '+%f%% Mienenertrag',
	'Energy'			=> '+%f%% Energieerzeugung',
	'ResourceStorage'	=> '+%f%% Speicher',
	'ShipStorage'		=> '+%f%% Flottenkapazität',
	'FlyTime'			=> '+%f%% Flugzeit',
	'FleetSlots'		=> '+%f%% Flottenslots',
	'Planets'			=> '+%f%% Planeten',
);
					
$LNG['tech'] = array(
	0 => 'Costruzione',
	1 => 'Miniera di Metallo',
	2 => 'Miniera di Cristalli',
	3 => 'Sintetizzatore di Deuterio',
	4 => 'Centrale Solare',
	6 => 'Centro di Ricerca Sperimentale',
	12 => 'Centrale a Fusione',
	14 => 'Fabbrica dei Robots',
	15 => 'Fabbrica dei Naniti ',
	21 => 'Cantiere Spaziale ',
	22 => 'Deposito di Metallo',
	23 => 'Deposito di Cristalli',
	24 => 'Cisterna di Deuterio',
	31 => 'Laboratorio di Ricerca',
	33 => 'Terraformer',
	34 => 'Base di appoggio',
	44 => 'Base Missilistica',
	40 => 'Costruzione Lunare',
	41 => 'Avamposto Lunare',
	42 => 'Falange di Sensori',
	43 => 'Portale Iperspaziale',

	100 => 'Ricerca',
	106 => 'Tecnologie per lo spionaggio',
	108 => 'Tecnologia informatica',
	109 => 'Tecnologia delle Armi',
	110 => 'Tecnologia degli Scudi',
	111 => 'Tecnologia delle Corazze',
	113 => 'Tecnologia Energetica',
	114 => 'Tecnologia Iperspaziale',
	115 => 'Propulsore a Combustione',
	117 => 'Propulsore a Impulso',
	118 => 'Propulsore Iperspaziale',
	120 => 'Tecnologia dei Laser',
	121 => 'Tecnologia Ionica',
	122 => 'Tecnologia dei Plasmi',
	123 => 'Rete Interplanetaria di Ricerca',
	124 => 'Astrofisica',
	131 => 'Produzione di Metallo',
	132 => 'Produzione di Cristallo',
	133 => 'Produzione di Deuterio',
	199 => 'Tecnologia Gravitonica',

	200 => 'Navi',
	202 => 'Cargo Leggero',
	203 => 'Cargo Pesante',
	204 => 'Caccia Leggero',
	205 => 'Caccia Pesante',
	206 => 'Incrociatore',
	207 => 'Nave da Battaglia',
	208 => 'Colonizzatrice',
	209 => 'Riciclatrice',
	210 => 'Sonda spia',
	211 => 'Bombardiere',
	212 => 'Satellite Solare',
	213 => 'Cacciatorpediniere',
	214 => 'Corazzata',
	215 => 'Incrociatore da Battaglia',
	216 => 'Morte Nera',
	217 => 'Cargo Avanzato',
	218 => 'Avatar',
	219 => 'Giga Riciclatrice',
	220 => 'Collezionista MO Intergalattica',

	400 => 'Difesa',
	401 => 'Lanciamissili',
	402 => 'Laser Leggero',
	403 => 'Laser Pesante',
	404 => 'Cannone Gauss',
	405 => 'Cannone Ionico',
	406 => 'Cannone al Plasma',
	407 => 'Cupola Scudo',
	408 => 'Cupola Scudo Potenziata',
	409 => 'Scudo Atmosferico',
	410 => 'Cannone Gravitonico',
	411 => 'Globo Difensivo Orbitale',

	502 => 'Missili Anti Balistici',
	503 => 'Missili Interplanetari',

	600 => 'Ufficiali',
	601 => 'Geologo',
	602 => 'Ammiraglio',
	603 => 'Ingenere',
	604 => 'Tecnico',
	605 => 'Costruttore',
	606 => 'Scienziato',
	607 => 'Magazziniere',
	608 => 'Ministro della Difesa',
	609 => 'Guardiano',
	610 => 'Spia',
	611 => 'Comandante',
	612 => 'Distruttore',
	613 => 'Generale',
	614 => 'Conquistatore',
	615 => 'Imperatore',

	700 => 'Caratteristiche Premium',
	701 => 'Ottimizzatore delle Armi',
	702 => 'Otimizzatore degli Scudi',
	703 => 'Coordinatore di Costruzioni',
	704 => 'Ottimizzatore delle Risorse',
	705 => 'Ottimizzatore di Energia',
	706 => 'Ottimizzazione di Ricerche',
	707 => 'Cooridnatore di Flotte',

	900 => 'Risorse',
	901 => 'Metallo',
	902 => 'Cristallo',
	903 => 'Deuterio',
	911 => 'Energia',
	921 => 'Materia Oscura',
);

$LNG['shortDescription'] = array(
	1 => 'La miniera di metallo fornisce le risorse base per un impero emergente e permette la realizzazione di costruzioni e navi.',
	2 => 'I cristalli sono la principale risorsa utilizzata per la costruzione di componenti elettronici e per la formazione di alcune leghe metalliche.',
	3 => 'Il deuterio è utilizzato come carburante per le navi stellari ed è estratto nelle profondità oceaniche. Il deuterio è una sostanza rara e perciò relativamente costosa.',
	4 => 'Le centrali ad energia solare convertono l\'energia fotonica solare in energia elettrica da utilizzarsi per alimentare la maggior parte delle strutture.',
	6 => 'Istruiamo i nostri scienziati, diffondiamo il sapere tra il popolo. Ogni livello di questo edificio riduce del 8% il tempo di ricerca.',
	12 => 'Una centrale a fusione nucleare produce un atomo di elio partendo da due di deuterio utilizzando pressioni e temperature estremamente alte.',
	14 => 'Le fabbriche dei robots forniscono unità di costruzione economiche ed affidabili che possono essere usate per costruire o migliorare qualsiasi struttura planetaria. Ogni livello aggiuntivo aumenta l\'efficienza e la quantità di unità robotiche che aiutano la costruzione.',
	15 => 'La fabbrica dei naniti è l\'ultima evoluzione della robotica. Ogni livello aggiuntivo fornisce naniti sempre più efficienti e sempre in maggiore quantità, utili per aumentare la velocità di costruzione.',
	21 => 'Il cantiere spaziale è il luogo dove vengono costruite le navi e le difese planetarie.',
	22 => 'Deposito di stoccaggio per metallo grezzo.',
	23 => 'Deposito di stoccaggio per cristalli non processati.',
	24 => 'Sono cisterne che contengono il deuterio appena prodotto in attesa d\'utilizzo.',
	31 => 'Il laboratorio è indispensabile per compiere ricerche su nuove tecnologie.',
	33 => 'Il terraformer è richiesto per rendere edificabili aree del tuo pianeta altrimenti inaccessibili.',
	34 => 'La base d\'appoggio offre la possibilità di rifornirsi alle flotte amiche in orbita che aiutano a difenderti.',
	41 => 'Dato che la luna non ha atmosfera, bisogna avere un avamposto lunare per generare uno spazio abitabile. Ogni livello aggiunge 3 spazi lunari che possono essere usati per costruire infrastrutture.',
	42 => 'Usando la falange di sensori le flotte di altri imperi possono essere scovate ed osservate. Una maggiore grandezza dei dispositivi della falange portano ad una maggiore portata dei sensori.',
	43 => 'I portali iperspaziali sono enormi impianti ricetrasmittenti e sono capaci di inviare anche la più grande flotta istantaneamente ad un altro portale.',
	44 => 'La base missilistica è una struttura di lancio e di stoccaggio di missili planetari.',

	106 => 'Studiando la tecnologia da applicare allo spionaggio potrete ottenere informazioni riguardanti gli altri pianeti.',
	108 => 'Maggiore è il livello della tecnologia informatica, più si avranno posti nella flotta. Ogni livello aggiuntivo permette di avere un posto in più nella propria flotta.',
	109 => 'Questo tipo di tecnologia aumenta l\'efficacia dei tuoi armamenti dove ogni livello aggiuntivo aumenta la potenza di fuoco del 10% ad ogni tipo di arma.',
	110 => 'La tecnologia degli scudi è utilizzata per generare uno scudo protettivo a particelle attorno alle strutture. Ogni livello migliora la schermatura del 10% rispetto al livello base di una data struttura.',
	111 => 'Leghe altamente sofisticate aiutano ad aumentare la corazzatura di una nave aggiungendo il 10%, rispetto alla struttura base, di forza per livello.',
	113 => 'Comprendendo la tecnologia che sta dietro i vari tipi di energia, possono esserne adottate di nuove e più avanzate. La tecnologia energetica è di somma importanza per un laboratorio moderno.',
	114 => 'Incorporando la quarta e la quinta dimensione nelle tecnologie di propulsione si rende disponibile un nuovo sistema di propulsione, molto più efficiente e che usa meno carburante dei sistemi tradizionali.',
	115 => 'Effettuare ricerche in questo campo fornisce propulsori a combustione sempre più veloci nonostante ogni livello aggiunga solo il 10% di velocità rispetto al motore base.',
	117 => 'Il propulsore a impulso si basa sul principio di repulsione delle particelle. La materia respinta è in realtà costituita dalle scorie generate dal reattore a fusione che fornisce l\'energia per questo tipo di propulsione.',
	118 => 'Il propulsore iperspaziale permette di entrare nell\'iperspazio attraverso una finestra iperspaziale in modo da ridurre estremamente i tempi di viaggio. L\'iperspazio è uno spazio alternativo con più di tre dimensioni.',
	120 => 'Il fascio di luce genera un raggio in grado di danneggiare l\'oggetto che ne viene colpito.',
	121 => 'La tecnologia delle armi ioniche studia come focalizzare un fascio di ioni accelerati su un bersaglio creando seri danni grazie agli scudi che sono per natura caricati elettricamente.',
	122 => 'Sviluppando ulteriormente la tecnologia ionica si arriva a sviluppare le armi alimentate a plasma, che usano scariche di plasma accelerato che può creare danni enormi al bersaglio.',
	123 => 'Gli scienziati dei tuoi pianeti possono comunicare tra loro attraverso questa rete.',
	124 => 'Con un modulo di ricerca astrofisica, le navi possono prendere parte a lunghe spedizioni. Ogni secondo livello di questa tecnologia permetterà la colonizzazione di un ulteriore pianeta.',
	131 => '2% in più di produzione nelle miniere di metallo',
	132 => '2% in più di produzione nelle miniere di cristallo',
	133 => '2% in più di produzione di sintetizzatore di deuterio',
	199 => 'Sparando delle particelle gravitoniche concentrate si crea un campo gravitazionale artificiale la cui potenza e forza attrattiva possono non solo distruggere navi ma addirittura lune intere.',

	202 => 'I cargo leggeri sono mezzi molto agili usati per trasportare risorse da un pianeta ad un altro.',
	203 => 'I cargo pesanti sono una versione avanzata delle più piccole navi cargo, rendendo disponibile più spazio per il carico e maggiore velocità dato il sistema di propulsione migliorato.',
	204 => 'Il caccia leggero è una nave manovrabile che si trova su quasi tutti i pianeti. I costi non sono particolarmente elevati ma allo stesso tempo la forza degli scudi e lo spazio per il trasporto sono molto limitati.',
	205 => 'Il caccia pesante è la diretta evoluzione del caccia leggero ed offre una corazzatura maggiore ed una più grande potenza d\'attacco.',
	206 => 'Gli incrociatori hanno una corazza almeno tre volte più potente dei caccia pesanti e hanno a disposizione più del doppio di potenza d fuoco. La loro velocità di crociera è allo stesso modo superiore ad ogni altra cosa vista prima.',
	207 => 'Le navi da battaglia sono la spina dorsale di ogni flotta militare. Corazzatura rinforzata, armamenti pesanti e alte velocità di spostamento, fanno di questa nave, insieme al grande spazio per il cargo, un nemico difficile da battere.',
	208 => 'I pianeti vuoti possono essere colonizzati grazie a questa nave.',
	209 => 'Le Navi Riciclatrici sono usate per raccogliere detriti che fluttuano nello spazio e riciclare risorse utili.',
	210 => 'Le sonde spia sono piccoli droni non pilotati dall\'uomo con sistemi di propulsione eccezionalmente veloci usati per spiare mondi stranieri.',
	211 => 'Il bombardiere è una nave stellare speciale sviluppata per sfondare pesanti difese planetarie.',
	212 => 'I satelliti solari sono semplici satelliti in orbita equipaggiati di celle fotovoltaiche e servono a trasferire energia al pianeta. L\'energia in questo modo è trasmessa a terra utilizzando un raggio laser speciale.',
	213 => 'Il cacciatorpediniere è il re delle navi da guerra.',
	214 => 'La corazzata è la nave stellare più pesante mai vista e ha una potenza di fuoco mai eguagliata in precedenza.',
	215 => 'L\'Incrociatore da battaglia è altamente specializzato nell\'intercettare flotte nemiche.',
	216 => 'Non c\'è nulla di così grande e pericoloso come una morte nera che si avvicina.',
	217 => 'E\' un\'evoluzione del cargo pesante. Ha una capacità di carico maggiore e vola più veloce.',
	218 => 'Lo scenario peggiore in assoluto, anche se molto lentamente.',
	219 => 'E\' un gigantesco impianto di riciclo iper veloce.',
	220 => 'Con questa nave è possibile, dopo anni di ricerca, la raccolta di materia oscura dalla luna.',

	401 => 'Il lanciamissili è un semplice ma indispensabile sistema di difesa.',
	402 => 'Con l\'utilizzo di un raggio laser concentrato si possono causare più danni che attraverso normali armi missilistiche.',
	403 => 'I laser pesanti hanno una potenza di emissione e un\'integrità strutturale superiore ai laser leggeri.',
	404 => 'Usando un\'enorme accelerazione elettromagnetica, il cannone gauss accelera pesanti proiettili.',
	405 => 'I cannoni ionici sparano raggi ionici altamente energetici verso i propri obiettivi destabilizzando gli scudi e distruggendo l\'elettronica.',
	406 => 'I cannoni al plasma liberano la potenza di una piccola eruzione solare nella forma di un proiettile di plasma. L\'energia distruttiva è addirittura superiore a quella della corazzata.',
	407 => 'La cupola scudo copre il pianeta con un sottile campo protettivo e di schermatura, che può assorbire enormi quantità di potenza di fuoco.',
	408 => 'La cupola scudo potenziata è un\' evoluta tecnologia di schermatura che assorbe ancor più energia prima di collassare.',
	409 => 'Lo sviluppo dello scudo atmosferico è il coronamento della tecnologia scudo. Si può utilizzare molto di più l\'energia per prevenire gli attacchi rispetto a qualsiasi altra cupola scudo.',
	410 => 'Dopo anni di ricerca sulle forze gravitazionali i ricercatori sono riusciti a sviluppare un cannone gravitonico che produce piccoli campi gravitazionali che possono essere focalizzati e sparati verso il nemico.',
	411 => 'Si tratta di una piattaforma difensiva stazionaria. Non ha alcuna trasmissione diretta con il pianeta ed è mantenuta in gravitazione nell\'orbita stabile. All\'inizio di questo processo richiede elevata massa di energia.',

	502 => 'I Missili Anti Balistici distruggono i missili interplanetari.',
	503 => 'I missili interplanetari distruggono le difese nemiche.',

	601 => 'Il Geologo è esperto in astromineralogia e cristallografia. Egli assiste la sua squadra in metallurgia e chimica, mentre si prende anche cura della comunicazione interplanetaria ottimizzando l\'utilizzo e raffinando i materiali grezzi in tutto l\'impero.',
	602 => 'L\'Ammiraglio di flotta è un esperto veterano di guerra e un brillante stratega. Nei combattimenti più complessi, egli è in grado di creare uno schema e di restare in contatto con gli ammiragli subordinati. Un saggio imperatore può contare sul suo aiuto in battaglia.',
	603 => 'L\'Ingegnere è specializzato nella gestione dell\'energia e delle difese. In tempi di pace, aumenta l\'energia prodotta dai pianeti, assicurando un\'adeguata distribuzione di energia attraverso tutte le griglie.',
	604 => 'La cooperativa dei Tecnici è composta da scienziati geniali, e vedrete che non hanno limiti; nessun altro comprenderebbe certe tecnologie. Nessun essere umano normale cercherà mai di decifrare il codice di un tecnico, egli inoltre, ispira i ricercatori dell\'impero con la sua sola presenza.',
	605 => 'Il Costruttore è un maestro nella progettazione degli edifici.',
	606 => 'La Gilda degli Scienziati è un assoziazione degli scienziati di maggior successo dell\'Impero. Essi sono specialisti nel migliorare la tecnologia.',
	607 => 'Il Magazziniere ha migliorato l\'abilità di stoccaggio e la capacità di smistamento. Con le tecniche di immagazzinamento avanzate e gli adeguamenti strutturali, può aumentare notevolemnte il volume di archiviazione utilizzabile di uno spazio.',
	608 => 'Il Ministro della Difesa è un membro dell\'esercito imperiale. Il suo entusiasmo e ambizione permettono di costruire una solida base fissa su ogni colonia a tempo di record.',
	609 => 'Il Guardiano ha visto il notevole lavoro che avete fatto nel suo regno. Per ringraziarvi, vi offre l\'opportunità di essere guardiano. Il Guardiano è la più alta onorificenza dell\'attività di deposito dell\'esercito imperiale.',
	610 => 'La Spia è una persona misteriosa. Nessuno conosce il suo vero volto, e tanto meno se è già morta.',
	611 => 'Il Comandante dell\'esercito imperiale è maestro nel trattare con la flotta. I suoi anni di esperienza con le flotte, con molte operazioni strategiche, sono una risorsa a qualsiasi sovrano.',
	612 => 'Il Distruttore è un ufficiale senza pietà. Egli rade al suolo i pianeti solo per il divertimento. Attualmente, ha scoperto un nuovo metodo per produrre armi di distruzione di massa.',
	613 => 'Il Generale è una persona venerabile, che ha servito molti anni nell\'esercito. Attraverso numerose manovre, il generale ha sviluppato strategie per ottimizzare la velocità di flotta, di diversi tipi di navi, in tutte le situazioni.',
	614 => 'L\'Imperatore ha notato in lui innegabili qualità di conquista. Egli gli ha proposto di diventare conquistatore. Il Conquistatore è il grado di educazione più alto dell\'esercito imperiale.',
	615 => 'Come si scopre, sei un grande conquistatore dell\'universo. E\' tempo per avere il posto che ti sei meritato.',

	701 => 'Il bonus è solo temporaneo.',
	702 => 'Il bonus è solo temporaneo.',
	703 => 'Il bonus è solo temporaneo.',
	704 => 'Il bonus è solo temporaneo.',
	705 => 'Il bonus è solo temporaneo.',
	706 => 'Il bonus è solo temporaneo.',
	707 => 'Il bonus è solo temporaneo.',
);

$LNG['longDescription'] = array(
	1 => 'Il metallo rappresenta la risorsa di base necessaria per la costruzione del tuo impero, esso consente infatti di realizzare costruzioni, navi, sistemi di difesa. Il metallo è la materia prima più economica, la sua estrazione richiede infatti un basso dispendio energetico e proprio per questo esso è molto più usato delle altre risorse. Il metallo si trova a profondità molto elevate, questo comporta la costruzione di miniere sempre più profonde e quindi un consumo maggiore di energia per farle funzionare.',
	2 => 'Baut Mineralien ab, die für die Feinelektronik benötigt werden. Sie benötigt jedoch mehr, da sie die Mineralien gleich in nötige Legierungen verarbeitet.',
	3 => 'Deuterium ist schwerer Wasserstoff. Daher sind ähnlich wie bei den Minen die grössten Vorräte auf dem Grund des Meeres. Der Ausbau des Synthetisierers sorgt ebenfalls für die Erschließung dieser Deuterium-Tiefenlagerstätten. Deuterium wird als Treibstoff für die Schiffe, für fast alle Forschungen, für einen Blick in die Galaxie sowie für den Sensorphalanx-Scan benötigt.',
	4 => 'Um die Energie zur Versorgung der Minen und Synthetisierern zu gewährleisten, sind riesige Solarkraftwerkanlagen von Nöten. Je größer die Anlagen ausgebaut sind, desto mehr Oberfläche ist mit photovoltaischen Zellen bedeckt, welche Lichtenergie in elektrische Energie umwandeln. Solarkraftwerke stellen den Grundstock der planetaren Energieversorgung dar.',
	6 => 'Aufgrund der immer zeitaufwendigeren Forschungen, haben sich die klügsten Köpfe der intergalaktischen Forschungsnetzwerke zusammengetan und den TechnoDome entwickelt. Es verkürzt die Forschungszeiten um 8%',
	12 => 'Im Atomkraftwerk werden Atome gespalten, umso mehr Energie zu erzeugen als in dem Solarkraftwerk, allerdings ist es teurer im Bau.',
	14 => 'Roboterfabriken stellen einfache Arbeitskräfte zur Verfügung, die beim Bau der planetaren Infrastruktur eingesetzt werden können. Jede Stufe erhöht damit die Geschwindigkeit des Ausbaus von Gebäuden.',
	15 => 'Die Nanitenfabrik ist die Krönung der Robotertechnik. Naniten sind nanometergroße Roboter, die durch Vernetzung zu außerordentlichen Leistungen im Stande sind. Einmal erforscht erhöhen sie die Produktivität in fast allen Bereichen. Die Nanitenfabrik halbiert pro Stufe die Bauzeit von Gebäuden, Schiffen und Verteidigungsanlagen.',
	21 => 'In der planetaren Werft werden alle Arten von Schiffen und Verteidigungsanlagen gebaut. Je größer sie ist, desto schneller können aufwändigere und größere Schiffe und Verteidigungsanlagen gebaut werden. Durch Anbau einer Nanitenfabrik werden winzige Roboter erstellt, die den Arbeitern helfen, schneller zu arbeiten.',
	22 => 'Riesige Lagerstätte für abgebautes Metallerz. Je größer der Speicher, desto mehr Metall kann in ihm gelagert werden. Ist das Lager voll, wird kein Metall mehr abgebaut.',
	23 => 'Das noch unbearbeitete Kristall wird in diesen riesigen Lagerhallen zwischengespeichert. Je größer das Lager, desto mehr Kristall kann in ihm eingelagert werden. Sind die Kristalllager voll, wird kein weiteres Kristall abgebaut.',
	24 => 'Riesige Tanks zur Lagerung des neu gewonnenen Deuteriums. Diese Lager findet man meistens in der Nähe von Raumhäfen. Je größer sie sind, desto mehr Deuterium kann in ihnen gelagert werden. Sind sie gefüllt, wird kein Deuterium mehr abgebaut.',
	31 => 'Um neue Technologien zu erforschen, ist der Betrieb einer Forschungsstation notwendig. Die Ausbaustufe einer Forschungsstation ist ausschlaggebend dafür, wie schnell eine neue Technologie erforscht werden kann. Je höher die Ausbaustufe des Labors, umso mehr neue Technologien können erforscht werden. Um die Forschungsarbeiten möglichst schnell zum Abschluss zu bringen, werden, wenn auf einem Planeten geforscht wird, automatisch alle verfügbaren Forscher in diese Forschungsstation geschickt und stehen somit auf anderen Planeten nicht mehr zur Verfügung. Sobald eine Technologie einmal erforscht ist, kehren die Forscher auf ihre Heimatplaneten zurück und bringen das Wissen um sie mit. So kann man die Technologie auf all seinen Planeten einsetzen.',
	33 => 'Mit zunehmendem Ausbau der Planeten, wurde die Frage des begrenzten Lebensraums auf Kolonien immer wichtiger. Traditionelle Methoden wie Hoch- und Tiefbau erwiesen sich zunehmend als unzureichend. Eine kleine Gruppe von Hochenergiephysikern und Nanotechnikern fand schließlich die Lösung: Das Terraforming. Unter Aufwand riesiger Energiemengen kann der Terraformer ganze Landstriche oder gar Kontinente urbar machen. In diesem Gebäude werden fortwährend eigens dafür konstruierte Naniten produziert, die für eine konstante Qualität des Bodens sorgen. Einmal gebaut kann der Terraformer nicht wieder abgerissen werden.',
	34 => 'Das Allianzdepot bietet die Möglichkeit, befreundete Flotten, die bei der Verteidigung helfen und im Orbit stehen, mit Treibstoff zu versorgen. Für jeden Ausbaulevel des Allianzdepots können 10.000 Einheiten Deuterium pro Stunde an die zu versorgenden Flotten im Orbit geschickt werden.',
	41 => 'Ein Mond verfügt über keinerlei Atmosphäre, deshalb muss vor der Besiedlung eine Mondbasis errichtet werden. Diese sorgt für die nötige Atemluft, Gravitation und Wärme. Je höher die Ausbaustufe der Mondbasis ist, umso größer ist die Fläche die mit einer Biosphäre versorgt wird. Pro Mondbasislevel können 3 Felder bebaut werden bis zum Maximum der Mondgröße. Diese beträgt (Durchmesser des Mondes/1000)^2, wobei jede Stufe der Mondbasis selbst auch ein Feld belegt Einmal gebaut kann die Mondbasis nicht wieder abgerissen werden.',
	42 => 'Hochauflösende Sensoren scannen das vollständige Frequenzspektrum aller auf die Phalanx auftreffenden Strahlungen. Hochleistungscomputer kombinieren winzige Energieschwankungen und gewinnen so Informationen über Schiffsbewegungen auf entfernten Planeten. Für den Scan muss Energie in Form von Deuterium (5.000) auf dem Mond bereitgestellt werden. Man scannt, indem man vom Mond aus ins Galaxiemenü wechselt und auf einen feindlichen Planeten in Sensorenreichweite (Phalanxstufe)^2 - 1 klickt.',
	43 => 'Sprungtore sind riesige Transmitter, die in der Lage sind, selbst große Flotten ohne Zeitverlust durch das Universum zu versenden. Diese Transmitter verbrauchen kein Deuterium, jedoch muss zwischen 2 Sprüngen eine Stunde vergehen, da sich die Tore sonst überhitzen würden. Auch ist ein Mitschicken von Ressourcen nicht möglich. Der ganze Vorgang erfordert eine ungeheuer hoch entwickelte Technologie.',
	44 => 'Raketensilos dienen zum Einlagern von Raketen. Pro ausgebauter Stufe kann man fünf Interplanetar- oder zehn Abfangraketen einlagern. Eine Interplanetarrakete benötigt so viel Platz wie zwei Abfangraketen. Unterschiedliche Raketentypen können beliebig kombiniert werden.',
	
	106 => 'La tecnologia per lo spionaggio è l\'evoluzione della tecnologia dei sensori. Più la tecnica è avanzata, maggiori saranno le informazioni che l\'utente avrà a disposizione relativamente ai processi che avvengono nei suoi immediati dintorni. Nel caso delle sonde, la differenza tra il proprio livello di spionaggio e quello degli avversari è decisiva. Più la propria tecnica di spionaggio sarà avanzata, più il rapporto conterrà maggiori informazioni: di conseguenza diminuirà la possibilità che un\'azione di spionaggio venga scoperta. Tanto più elevato è il numero di sonde che vengono spedite in una missione, quanto maggiori saranno i dettagli che verranno trasmessi dai pianeti obiettivo. Allo stesso tempo aumenterà però anche la possibilità di essere scoperti. Ad ogni modo, la tecnologia per lo spionaggio consente di migliorare la localizzazione delle flotte di terzi. A questo proposito il proprio livello di spionaggio è decisivo. A partire dal livello 2, oltre alla notifica di attacco viene mostrato anche il numero totale delle navi attaccanti. A partire dal livello 4 vengono mostrati il tipo di navi attaccanti ed il loro numero totale e dal livello 8 il numero preciso dei diversi tipi di nave. Questa tecnica risulta irrinunciabile in caso di attacco imminente, essa consente infatti di scoprire se l\'avversario dispone o meno di flotte e/o di difesa. Per questo motivo è fondamentale iniziare il prima possibile ad analizzare questa tecnica.',
	108 => 'La tecnologia informatica viene utilizzata per costruire unità processuali e di controllo dati sempre più potenti. Ogni livello aumenta la potenza di calcolo e il livello di parallelismo. Più questa tecnologia è sviluppata, maggiori saranno i posti nella flotta. Più posti ha un impero, maggiore sarà l\'attività che genera introiti. I posti nella flotta sono utilizzati per navi militari come per cargo o manovre di spionaggio, è una buona idea aumentare costantemente la ricerca in quest\'area per fornire un\'adeguata flessibilità alla flotta.',
	109 => 'Le tecnologie delle armi cercano di sviluppare ulteriormente le armi disponibili. Esse sono principalmente focalizzate nell\'aumento della potenza e efficienza dei sistemi d\'armamento. In questo modo aumentando il livello di questa tecnologia la stessa arma ha più potenza di fuoco e fa più danni - ogni livello aggiunge il 10% rispetto alla potenza base. Siccome la tecnologia degli armamenti è importante per stare al passo con i nemici, è una buona idea aumentare continuamente le conoscenze in questo campo.',
	110 => 'La tecnologia degli scudi è utilizzata per generare uno scudo protettivo a particelle attorno alle strutture. Ogni livello migliora la schermatura del 10% rispetto al livello base di una data struttura. I livelli aggiuntivi aumentano la quantità di energia che uno scudo può assorbire prima di cedere. Gli scudi non sono solo usati sulle navi, ma anche per cupole protettive planetarie.',
	111 => 'Leghe altamente sofisticate aiutano ad aumentare la corazzatura di una nave aggiungendo il 10%, rispetto alla struttura base, di forza per livello. Per una data lega risultata efficace, può essere alterata la struttura molecolare per manipolarne il comportamento in situazioni di combattimento e per incorporare le ultime scoperte tecnologiche.',
	113 => 'La tecnologia energetica ha a che fare con la conoscenza e il raffinamento delle sorgenti di energia, dei problemi di stoccaggio e delle tecnologie che forniscono il componente fondamentale di oggi: l\'energia. Più questa tecnologia è sviluppata, più saranno efficienti i tuoi sistemi. Certi livelli di avanzamento sono addirittura richiesti per poter raggiungere altre tecnologie specifiche che si basano sulla conoscenza dell\'energia.',
	114 => 'Incorporando la quarta e la quinta dimensione nelle tecnologie di propulsione si rende disponibile un nuovo sistema di proulsione, molto più efficiente e che usa meno carburante dei sistemi tradizionali. Inoltre la tecnologia iperspaziale fornisce la base per i viaggi iperspaziali che sono usati dalle grandi navi da guerra (come i portali dimensionali). È una nuova e complicata tecnologia questa che richiede equipaggiamenti di laboratorio e strutture di test dispendiose.',
	115 => 'I propulsori a combustione appartengono alla più vecchia categoria di motori esistenti e sono basati sulla repulsione. Le particelle sono accelerate e lasciano il motore generando una forza repulsiva che fa muovere la nave nella direzione opposta. L\'efficienza di questi motori a combustione è bassa ma sono anche poco costosi da costruire e hanno dato prova di affidabilità. Le loro dimensioni sono piccole e non richiedono un processo troppo dispendioso per il controllo. Fare ricerca ad alti livelli garantisce motori sempre più veloci, dato che ogni livello aggiunge il 10% di velocità rispetto al livello base. Siccome questa tecnologia è tra le più importanti per un impero emergente, bisognerebbe condurre ricerche al più presto.',
	117 => 'Il propulsore a impulso si basa sul principio di repulsione delle particelle. La materia respinta è in realtà costituita dalle scorie generate dal reattore a fusione che fornisce l\'energia per questo tipo di propulsione. I motori ad impulso sono uno sviluppo dei motori a combustione ed aumentano l\'efficienza di questi, diminuendone i consumi in funzione della velocità.',
	118 => 'Attraverso la curvatura dello spazio-tempo nell\'ambiente circostante l\'astronave, lo spazio viene compresso ad un tal grado che grandi distanze possono essere attraversate in un breve periodo di tempo. Più è avanzato lo sviluppo del motore, maggiore sarà la compressione dello spazio, aumentando così la velocità del 30% per ogni livello.',
	120 => 'Il LASER (Light Amplification by Stimulated Emission of Radiation) è un raggio fotonico monocromatico e coerente con una focalizzazione estremamente precisa. Le unità laser hanno un\'ampia gamma di utilizzo: dalla navigazione giroscopica ai computer ottici o sistemi d\'armamento, la tecnologia laser è fondamentale per ogni impero.',
	121 => 'La tecnologia delle armi ioniche studia come focalizzare un fascio di ioni accelerati su un bersaglio creando seri danni grazie agli scudi che sono per natura caricati elettricamente. I raggi ionici sono superiori ai laser ma hanno costi di ricerca maggiori. Nonostante siano piuttosto semplici rispetto ad altre tecnologie, i raggi ionici non sono usati spesso.',
	122 => 'Le armi al plasma sono più pericolose di ogni altro armamento conosciuto, a causa della natura dannosa del plasma. Esso è uno dei quattro stati della materia (solido, liquido, gas, plasma) ed è composto da un ugual numero di particelle gassose cariche positivamente e negativamente. Il plasma può essere prodotto da un gas se si utilizza abbastanza energia da causare la ionizzazione dello stesso in nuclei carichi positivamente ed elettroni. Queste particelle cariche vengono compattate in "scariche" usando tecniche magnetiche e rendendo possibile sparare le scariche.',
	123 => 'Gli scienziati dei tuoi pianeti possono comunicare tra loro attraverso questa rete. Per ogni livello di ricerca il tuo laboratorio con livello più alto che non sia già collegato al network, verrà aggiunto alla rete. Quando la rete sarà stabilita, i loro livelli si sommeranno. Ogni laboratorio collegato deve avere il livello necessario per la tecnologia che si ha in programma di ricercare. In tal modo si unirà alla rete.',
	124 => 'Ulteriori scoperte nel campo dell\'astrofisica permettono la costruzione di laboratori che possono essere ospitati su più navi. Questo rende possibile lunghe spedizioni nelle inesplorate aree dello spazio. Inoltre, questi avanzamenti, possono essere utilizzati per colonizzare le galassie. Per ogni due livelli di questa tecnologia, può essere colonizzato un pianeta.',
	131 => 'La motivazione dei lavoratori delle miniere di metallo sale se si riconosce il loro duro lavoro. Massaggi gratuiti, una migliore qualità dei cibo nella mensa e una birra a fine giornata migliorano le prestazioni lavorative fino al 2% all\'ora. ',
	132 => 'La motivazione dei lavoratori delle miniere di cristallo sale se si riconosce il loro duro lavoro. Massaggi gratuiti, una migliore qualità dei cibo nella mensa e una birra a fine giornata migliorano le prestazioni lavorative fino al 2% all\'ora. ',
	133 => 'La motivazione dei lavoratori delle miniere di deuterio sale se si riconosce il loro duro lavoro. Massaggi gratuiti, una migliore qualità dei cibo nella mensa e una birra a fine giornata migliorano le prestazioni lavorative fino al 2% all\'ora.',
	199 => 'Un gravitone è una particella elementare responsabile degli effetti della gravità. Essa non ha massa a riposo, non è carica e ha spin pari a due. Sparando delle particelle gravitoniche concentrate si crea un campo gravitazionale artificiale la cui potenza e forza attrattiva possono non solo distruggere navi ma addirittura lune intere. Per poter produrre la quantità necessaria di gravitoni il pianeta deve poter generare un immensa quantità di energia.',
	
	202 => 'I cargo leggeri sono grandi, approssimativamente, come i caccia ma hanno motori ed armamenti meno efficienti in modo da ricavare più spazio per il cargo. Il cargo leggero può contenere 5000 risorse. Data la limitata potenza di fuoco, spesso sono accompagnati da altre navi nelle loro missioni. La velocità base dei cargo leggeri è aumentata non appena viene ricercato il motore a impulso di livello 5 in quanto essi vengono equipaggiati con motori a impulso.',
	203 => 'Questo tipo di nave non dovrebbe mai fare missioni da sola perché non ha armamenti seri od altre tecnologie, in modo da fornire il massimo spazio per il trasporto. I cargo pesanti possono velocemente rifornire pianeti grazie anche ai suoi motori a combustione altamente sofisticati. Naturalmente esso accompagna la flotta sui pianeti attaccati per recuperare tante più risorse quanto possibile.',
	204 => 'Data la loro corazza leggera e il semplice sistema d\'armamento, i caccia leggeri appartengono alle navi di supporto in battaglia. La loro agilità e velocità insieme alla quantità di navi che attaccano, può farle apparire come un diversivo rispetto alle navi più grandi che non sono così manovrabili.',
	205 => 'Durante lo sviluppo del caccia leggero i ricercatori sono arrivati al punto in cui la guida convenzionale raggiunse i propri limiti. Per fornire l\'agilità necessaria ai nuovi caccia, è stato usato per la prima volta un motore ad impulso. Nonostante i costi aggiuntivi e la complessità si sono rivelate nuove possibilità in parte grazie al maggior costo dei materiali generalmente utilizzati. Tramite l\'uso della tecnologia d\'impulso, è stata resa disponibile più energia per le armi e gli scudi. La corazzatura migliorata e un maggior numero di armi rendono questo caccia una minaccia molto maggiore rispetto ai suoi predecessori.',
	206 => 'Con la comparsa di laser pesanti e cannoni a ioni sui campi di battaglia, le navi da combattimento vennero sempre più sopraffatte. Nonostante le molte modifiche la potenza di fuoco e la corazzatura dello scafo non poterono essere migliorati a sufficienza per affrontare questi nuovi sistemi di difesa. Questo è il motivo per il quale è stato scelto di sviluppare un tipo di nave completamente nuovo, fornendo più corazzatura e armi più potenti. Così nacque l\'incrociatore. Gli incrociatori hanno una corazza almeno tre volte più potente dei caccia pesanti e hanno a disposizione più del doppio di potenza d fuoco. La loro velocità di crociera è allo stesso modo superiore ad ogni altra cosa vista prima. Non c\'è praticamente nessuna nave migliore contro le difese planetarie leggere o medie e perciò gli incrociatori sono stati ampiamente adottati in tutto l\'universo da almeno un centinaio di anni. Sfortunatamente con la creazione dei nuovi e potenti sistemi difensivi come il cannone di Gauss o gli emettitori di plasma, il regno degli incrociatori finì presto. Al giorno d\'oggi essi vengono ancora usati per combattere contro battaglioni di caccia dato l\'efficace sistema d\'armamento contro questi ultimi.',
	207 => 'Le navi da battaglia sono la spina dorsale di ogni flotta militare. La loro corazzatura rinforzata, abbinata a degli armamenti pesanti, e una velocità di crociera elevata, rendono questa nave indispensabile per ogni impero. Inoltre possiede un\'ampia stiva che è ottima in situazioni ostili.',
	208 => 'Nel ventesimo secolo, l\'uomo ha deciso di puntare verso le stelle. Dapprima, è atterrato sulla Luna. In seguito, è stata creata una stazione spaziale. Poco dopo, Marte fu colonizzato. Ben presto si capì che la nostra crescita sarebbe dipesa dalla colonizzazione di altri mondi. Gli scienziati e gli ingegneri di tutto il mondo si riunirono per sviluppare quella che diventò il più grande traguardo mai raggiunto dall\'uomo. Era nata la prima Colonizzatrice.<br />Questa nave è utilizzata per preparare per la colonizzazione un pianeta appena scoperto. Appena arriva a destinazione, si trasforma in spazio abitativo, per assistere i coloni durante la popolazione del nuovo mondo. Il massimo numero di pianeti colonizzabili è determinato dai progressi nella ricerca dell\'astrofisica. Due nuovi livelli di Astrofisica consentono la colonizzazione di un nuovo pianeta.',
	209 => 'I combattimenti nello spazio sembrano diventare sempre più grandi e in una singola battaglia migliaia di navi possono essere distrutte, con il rischio di perdere per sempre i detriti che vanno alla deriva. Le navi cargo standard non hanno il compito di raccogliere risorse importanti o anche semplicemente avvicinarsi ad esse. Con il nuovo sviluppo di navi stellari riciclatrici speciali, e basandosi sulla conoscenza in crescita riguardo alle tecnologie di schermatura, alla fine è diventato possibile raccogliere quei campi di importanti detriti. Le navi riciclatrici sono simili in dimensione alle navi cargo grandi, nonostante questo le installazioni addizionali tecniche necessarie per il compito richiedono maggiore spazio. E\' per questo che le navi riciclatrici hanno una capacità di deposito limitata a 20\'000.',
	210 => 'Le sonde spia sono piccoli droni che, con i loro sistemi di comunicazione altamente avanzati, posso inviare da grandi distanze informazioni di spionaggio in pochi secondi. Esse utilizzano le orbite dei pianeti per raccogliere informazioni e, allo stesso tempo, ridirigersi verso la terra madre. Durante la permanenza nell\'orbita nemica, esse sono particolarmente facili da rilevare. Non disponendo di copertura, scudi o sistemi d\'armamento, esse sono particolarmente vulnerabili alle strutture difensive.',
	211 => 'Il bombardiere è una nave stellare speciale sviluppata per sfondare pesanti difese planetarie. Grazie ad un sistema di puntamento con guida laser, possono essere sganciate bombe al plasma con precisione sul bersaglio, causando enorme distruzione tra i sistemi di difesa planetari.<br />La velocità base dei bombardieri è aumentata non appena viene ricercato il motore iperspaziale di livello 8 in quanto essi vengono equipaggiati con motori iperspaziali.',
	212 => 'I satelliti solari vengono lanciati nell\'orbita geostazionaria attorno ad un pianeta. Essi riuniscono in fasci l\'energia solare e la indirizzano ad un sistema riflettente posizionato a terra. L\'efficienza dei satelliti solari dipende dalla potenza dei raggi solari. Il rendimento energetico dei pianeti situati vicino al sole è normalmente più elevato rispetto a quello dei pianeti più lontani da esso. Grazie al vantaggioso rapporto qualità/prezzo, i satelliti solari sono utilizzati ad ampio raggio per risolvere i problemi a livello energetico. Va tuttavia tenuto in considerazione che i satelliti solari potrebbero venire distrutti durante i combattimenti.',
	213 => 'Il cacciatorpediniere è il re delle navi da guerra.


	 Seine Multiphalanx Ionen-, Plasma- und Gaußgeschütztürme können durch ihre verbesserten Anpeilungssensoren fast 99% der verteidigenden leichten Laser treffen.. 


	 Poiché il cacciatorpediniere è molto grande, la sua manovrabilità è molto limitata, esso assomiglia più a una stazione di battaglia piuttosto che a una nave da combattimento. Anche il suo consumo di deuterio è alto come suo potere di combattimento.',
	214 => 'Con la corazzata, la madre di tutte le navi da guerra entra nell\'arena. Il suo sistema multi-falange d\'armamento consiste di cannoni ionici, al plasma e di Gauss montati su torrette veloci nella risposta che permettono loro di eliminare i caccia operativi con un margine di successo del 99%. La dimensione della nave è d\'altro canto il suo svantaggio dal momento che la manovrabilità è limitata, facendo della corazzata più una stazione da combattimento che una nave da guerra. Il consumo di carburante di queste immense corazzate è però tanto alto quanto lo è il loro potere di fuoco...',
	215 => 'Questa nave, tecnologicamente avanzata, è mortale quando viene usata per distruggere le flotte d\'attacco. Con i suoi cannoni laser migliorati e un avanzato motore Iperspaziale, detiene una posizione privilegiata tra le navi pesanti, che è deputata a distruggere. A causa del suo design piccolo e del suo enorme armamento, la capacità di carico è minima; ma questo è compensato dal basso consumo di carburante.',
	216 => 'La morte nera è equipaggiata con un singolo gigantesco Cannone di Gauss in grado di distruggere praticamente qualsiasi cosa con un singolo colpo, sia che siano corazzate o lune. In modo da produrre l\'energia necessaria per quest\'arma, enormi parti all\'interno della Morte Nera sono utilizzate come generatori di potenza. La dimensione della Morte Nera inoltre ne limita la velocità negli spostamenti, che è molto bassa. Si dice che spesso il capitano aiuti a spingerla per aumentarne la velocità. Solo imperi immensi e avanzati hanno la manodopera e le conoscenze estese richieste per poter costruire una tale nave stellare della dimensione di una luna.',
	217 => 'E\' un\'evoluzione del cargo pesante. Ha una capacità di carico maggiore e vola più veloce.',
	218 => 'Alla vista della nave, la popolazione del pianeta cade nel terrore e lascia la colonia. Qualità combattimento eccellenti, ma molto lenta.',
	219 => 'Questa nave è una riciclatrice veramente enorme con velocità mozzafiato e capacità di carico enorme! Creato per grandi imperi.',
	220 => 'Dopo anni di studi sulla materia oscura, gli scienziati hanno imparato ad estrarla dai minerali lunari.',
	
	401 => 'Il lanciamissili è un semplice ma indispensabile sistema di difesa. Diventa abbastanza funzionale se in grandi quantità e può essere costruito senza specifiche ricerche perché è una semplice arma balistica. Il basso costo di produzione lo rende adeguato contro piccole flotte, ma diventa sempre meno efficace con l\'incremento dei sistemi di difesa. In successivi sviluppi risulta essere utilizzato solo come specchietto per le allodole nei combattimenti.<br />In generale, i sistemi di difesa si disattivano da soli quando raggiungono parametri operazionali critici in modo da lasciare la possibilità di riparazione. In media, il 70% delle difese planetarie distrutte può essere riportato in funzione dopo un combattimento.',
	402 => 'Per tenere il passo con la velocità di sviluppo sempre in aumento in termini di tecnologie aerospaziali, gli scienziati dovettero sviluppare un nuovo tipo di sistema di difesa in grado di gestire navi e flotte sempre più forti e meglio equipaggiate. In breve nacque l\'unità laser piccola, che era in grado di sparare sul bersaglio un raggio laser altamente concentrato e causare molto più danno dell\'impatto di missili balistici. Dall\'altro lato, fu migliorata la schermatura dei cannoni per gestire le maggiori potenze di fuoco delle moderne navi. Dal momento che il basso costo dell\'unità era un obiettivo essenziale designato, la struttura di base non è migliorata rispetto al lancia-missili. Poiché il laser leggero offre un vantaggioso rapporto qualità-prezzo, è il più conosciuto sistema di difesa essendo usato contemporaneamente da piccoli imperi in crescita e da grandi imperi multigalattici.',
	403 => 'Il laser pesante è la diretta evoluzione del sistema laser leggero, ha infatti una migliorata integrità strutturale e vi sono adottati nuovi materiali. In questo modo è stato possibile migliorare la struttura di copertura e grazie all\'installazione di nuovi sistemi computerizzati ed energetici, molta più energia, rispetto a quando si usavano le unità laser leggere, è rilasciata contro il bersaglio.',
	404 => 'Le armi a proiettili erano considerate obsolete date la moderna tecnologia di fusione nucleare, le nuove fonti di energia, la scoperta della tecnologia iperspaziale e la ulteriormente migliorata tecnologia delle leghe. Però è la stessa tecnologia energetica che una volta ne prese il posto, che ora le richiama indietro in modo da potersi muovere verso il nuovo secolo: il principio di base è da lungo conosciuto e si data a cavallo del 20esimo e 21esimo secolo: l\'acceleratore di particelle. Un cannone di Gauss in realtà non è altro che un acceleratore di particelle di enorme misura dove i proiettili di parecchie tonnellate di peso vengono accelerati utilizzando immense spirali elettromagnetiche. La velocità di uscita di questi grandi proiettili è così elevata da bruciare la polvere nell\'aria circostante e il rinculo del colpo scuote il terreno. Anche le tecnologie di schermatura e di leghe protettive più innovate con difficoltà resistono all\'impatto di tali proiettili - capita la maggior parte delle volte, che il proiettile semplicemente passi attraverso la struttura bersaglio.',
	405 => 'Nel 21esimo secolo esisteva una tecnologia chiamata EMP, che sta per impulso elettromagnetico. Un tale impulso energetico si dimostra principalmente pericoloso per i sistemi che utilizzano elettricità o sono sensibili ad essa. In quei tempi, tali armi erano trasportate in bombe o razzi missilistici, ma con il continuo sviluppo nell\'area degli EMP, è oggi possibile montare tali unità in semplici cannoni. Il cannone ionico è fino a questo punto il miglior equipaggiamento per queste armi. Il raggio ionico mirato distrugge sul bersaglio ogni sistema elettrico non schermato e destabilizza il sistema di scudi della nave stellare. In combinazione questo spesso significa la distruzione totale nonostante il fatto che gli esseri viventi non vengano colpiti direttamente. L\'unica nave che si sappia usi i cannoni ionici è l\'incrociatore da battaglia, a causa delle alte richieste di energia da parte di questi cannoni e il fatto che il combattimento spesso richieda la distruzione del bersaglio non il paralizzarlo.',
	406 => 'La tecnologia laser è stata portata quasi alla perfezione, la tecnologia ionica sembrava aver raggiunto il massimo e in generale non vi era visione di come sarebbe stato possibile ottenere un miglioramento degli esistenti sistemi d\'armamento. Ma questo cambierà una volta che sarà nata l\'idea di mettere assieme le due tecnologie. Mentre il laser è utilizzato per scaldare le particelle di deuterio a milioni di gradi, la tecnologia ionica carica elettricamente queste particelle e le conoscenze in elettromagnetismo permettono di contenere questo pericoloso plasma. La scarica blu del plasma è molto bella quando è in movimento verso il suo obiettivo, ma dal punto di vista dell\'equipaggio di una nave stellare, questa sfera di plasma apparentemente amichevole significa morte e distruzione. Gli armamenti al plasma sono identificati come le più pericolose minacce, ma hanno il loro costo.',
	407 => 'Molto prima che i generatori di scudi diventassero integrati e portatili, c\'erano vecchi grandi generatori sulla superficie dei pianeti. Quelli erano in grado di disporre una enorme cupola difensiva attorno alla superficie dell\'intero pianeta capace di assorbire grandi quantità di energia qualora subisse un attacco. Ogni tanto capita che un piccolo convoglio da combattimento venga abbattuto da queste cupole-scudo. Usando tecnologie di schermatura sempre più avanzate, queste cupole possono essere migliorate ulteriormente, così che la loro abilità di assorbire energia sia ancora più grande. Chiaramente solo una di ciascuna cupola-scudo può essere costruita su un pianeta.',
	408 => 'Questa è una versione avanzata della cupola scudo e la sua principale caratteristica è la maggiore capacità di assorbimento d\'energia. Si basa sulla stessa conoscenza tecnologica delle cupole più piccole. I generatori sono inoltre meno rumorosi quando in azione.',
	409 => 'L\'evoluzione della Cupola Scudo Potenziata. Essa si basa sulle stesse tecnologie, ma può essere utilizzata molta più energia per scoraggiare gli attacchi nemici.',
	410 => 'Essa si basa, come suggerisce il nome, sulla potenza di un gravitone, conosciuto dalla Morte Nera e dalle navi migliori.',
	411 => 'Questa piattaforma di dimensioni gigantesche, è la cosa più grande che l\'universo abbia mai visto. Si tratta di una piattaforma difensiva stazionaria. Non ha alcuna trasmissione diretta con il pianeta ed è mantenuta in gravitazione nell\'orbita stabile. All\'inizio di questo processo richiede elevata massa di energia. I ricercatori stanno lavorando per costruire su questa piattaforma le navi, che saranno utilizzate come un anello esterno di difesa, il che rende difficile per l\'avversario sfondare la difesa planetaria. A causa della enorme scala, è possibile avere uno solo di questi mostri.',
	
	502 => 'I missili anti balistici distruggono i missili attaccanti. Ogni missile anti balistico distrugge un missile interplanetario.',
	503 => 'I missili interplanetari distruggono le difese nemiche. Le difese distrutte dai missili interplanetari non verranno ricostruite.',

	601 => 'Il Geologo è esperto in astromineralogia e cristallografia. Egli assiste la sua squadra in metallurgia e chimica, mentre si prende anche cura della comunicazione interplanetaria ottimizzando l\'utilizzo e raffinando i materiali grezzi in tutto l\'impero. Utilizzando un equipaggiamento appropriato, è in grado di localizzare ottimi giacimenti, aumentando la produzione delle miniere.',
	602 => 'L\'Ammiraglio di flotta è un esperto veterano di guerra e un brillante stratega. Nei combattimenti più complessi, egli è in grado di creare uno schema e di restare in contatto con gli ammiragli subordinati. Un saggio imperatore può contare sul suo aiuto in battaglia.',
	603 => 'L\'Ingegnere è specializzato nella gestione dell\'energia e delle difese. In tempi di pace, aumenta l\'energia prodotta dai pianeti, assicurando un\'adeguata distribuzione di energia attraverso tutte le griglie. In caso di attacco nemico, dirotta tutta l\'energia disponibile alle difese, evitando sovraccarichi e riducendo il numero di difese perse durante la battaglia. ',
	604 => 'La cooperativa dei Tecnici è composta da scienziati geniali, e vedrete che non hanno limiti; nessun altro comprenderebbe certe tecnologie. Nessun essere umano normale cercherà mai di decifrare il codice di un tecnico, egli inoltre, ispira i ricercatori dell\'impero con la sua sola presenza.',
	605 => 'Il Costruttore è un maestro nella progettazione degli edifici.',
	606 => 'La Gilda degli Scienziati è un assoziazione degli scienziati di maggior successo dell\'Impero. Essi sono specialisti nel migliorare la tecnologia.',
	607 => 'Il Magazziniere ha migliorato l\'abilità di stoccaggio e la capacità di smistamento. Con le tecniche di immagazzinamento avanzate e gli adeguamenti strutturali, può aumentare notevolemnte il volume di archiviazione utilizzabile di uno spazio.',
	608 => 'Il Ministro della Difesa è un membro dell\'esercito imperiale. Il suo entusiasmo e ambizione permettono di costruire una solida base fissa su ogni colonia a tempo di record.',
	609 => 'Il Guardiano ha visto il notevole lavoro che avete fatto nel suo regno. Per ringraziarvi, vi offre l\'opportunità di essere guardiano. Il Guardiano è la più alta onorificenza dell\'attività di deposito dell\'esercito imperiale.',
	610 => 'La Spia è una persona misteriosa. Nessuno conosce il suo vero volto, e tanto meno se è già morta.',
	611 => 'Il Comandante dell\'esercito imperiale è maestro nel trattare con la flotta. I suoi anni di esperienza con le flotte, con molte operazioni strategiche, sono una risorsa a qualsiasi sovrano.',
	612 => 'Il Distruttore è un ufficiale senza pietà. Egli rade al suolo i pianeti solo per il divertimento. Attualmente, ha scoperto un nuovo metodo per produrre armi di distruzione di massa.',
	613 => 'Il Generale è una persona venerabile, che ha servito molti anni nell\'esercito. Attraverso numerose manovre, il generale ha sviluppato strategie per ottimizzare la velocità di flotta, di diversi tipi di navi, in tutte le situazioni.',
	614 => 'L\'Imperatore ha notato in lui innegabili qualità di conquista. Egli gli ha proposto di diventare conquistatore. Il Conquistatore è il grado di educazione più alto dell\'esercito imperiale.',
	615 => 'Come si scopre, sei un grande conquistatore dell\'universo. E\' tempo per avere il posto che ti sei meritato.',

	701 => 'Aumenta l\'armamento e la difesa delle navi.',
	702 => 'Aumenta la potenza dello scudo di difesa delle navi.',
	703 => 'Riduce il tempo di costruzione degli edifici.',
	704 => 'Aumenta la produzione di materie prime.',
	705 => 'Aumenta la produzione di energia.',
	706 => 'Riduce il tempo di ricerca.',
	707 => 'Riduce il tempo di volo delle navi.',	
);

?>